### PR TITLE
Fix/option persistence

### LINKED ISSUE #173: Importing settings with a deleted account set as the initial account results in login page being shown

### PR DESCRIPTION
**Pull request by Leptopoda**
Forgot to push this earlier.
Fixes the loading of `SelectOption` value when no values have been set yet.

### CODE REVIEW

**Comment by Leptopoda** [comment]
Still missing a unit test

File: packages/neon/neon/lib/src/settings/models/select_option.dart [hunk 1]
```diff
@@ -25,9 +32,27 @@ class SelectOption<T> extends Option<T> {
...
+    /// This only works when [T] is of type String.
+    final bool forceLoadValue = false,
     super.category,
   })  : _values = values,
-        super.depend(initialValue: _fromString(values, storage.getString(key)));
+        super.depend(initialValue: loadValue(values, storage.getString(key), forceLoad: forceLoadValue));
+
+  static T? loadValue<T>(final Map<T, LabelBuilder> vs, final String? stored, {final bool forceLoad = false}) {
+    if (forceLoad) {
+      assert(vs.isEmpty, 'Force loading should only be used when no initial valus are specified.');
```
Comment (provokateurin) [inline packages/neon/neon/lib/src/settings/models/select_option.dart:48]:
```suggestion
      assert(vs.isEmpty, 'Force loading should only be used when no initial values are specified.');
```

File: packages/neon/neon/lib/src/settings/models/select_option.dart [hunk 2]
```diff
@@ -12,10 +12,17 @@ class SelectOption<T> extends Option<T> {
     required super.label,
     required super.defaultValue,
     required final Map<T, LabelBuilder> values,
+
+    /// Force loading the stored value.
+    ///
+    /// This is needed when [values] is empty but the stored value should still
+    /// be loaded.
+    /// This only works when [T] is of type String.
+    final bool forceLoadValue = false,
```
Comment (provokateurin) [inline packages/neon/neon/lib/src/settings/models/select_option.dart:21]: Can't we just always force load? I fear that future devs will forget to set this option manually

**Review by provokateurin — CHANGES_REQUESTED** [review]

File: packages/neon/neon/lib/src/settings/models/select_option.dart (hunk 2 above)
Comment (Leptopoda) [reply packages/neon/neon/lib/src/settings/models/select_option.dart:21]: What about keeping forceLoadValue and defaulting to true?

Comment (provokateurin) [reply packages/neon/neon/lib/src/settings/models/select_option.dart:21]: Is the false value useful for anything if it is broken without it?

Comment (Leptopoda) [reply packages/neon/neon/lib/src/settings/models/select_option.dart:21]: It's not strictly broken.
The problem only occurs when `values` is empty when initializing.

Force loading will only work when the generic is of type `String` as we wouldn't know how to desetialize it without values being set.

It just so happens that we mostly use Strings (the ID of something) and use late loading quite some times

Comment (provokateurin) [reply packages/neon/neon/lib/src/settings/models/select_option.dart:21]: Ah, makes sense. How about only defaulting to true if the type is String?

**Comment by Leptopoda** [comment]
I couldn't test/verify the updated branch yet.

**Comment by Leptopoda** [comment]
@provokateurin  I verified it with the initial app option

File: packages/neon/neon/lib/src/settings/models/select_option.dart [hunk 3]
```diff
@@ -12,10 +12,17 @@ class SelectOption<T> extends Option<T> {
     required super.label,
     required super.defaultValue,
     required final Map<T, LabelBuilder> values,
+
+    /// Force loading the stored value.
+    ///
+    /// This is needed when [values] is empty but the stored value should still
+    /// be loaded.
```
Comment (provokateurin) [inline packages/neon/neon/lib/src/settings/models/select_option.dart:19]: Can this be on one line? (same for the comment further down)

File: packages/neon/neon/lib/src/settings/models/select_option.dart [hunk 4]
```diff
@@ -25,9 +32,24 @@ class SelectOption<T> extends Option<T> {
     required super.defaultValue,
     required final Map<T, LabelBuilder> values,
     required super.enabled,
+
+    /// Force loading the stored value.
+    ///
+    /// This is needed when [values] is empty but the stored value should still
+    /// be loaded.
+    /// This only works when [T] is of type String?.
```
Comment (provokateurin) [inline packages/neon/neon/lib/src/settings/models/select_option.dart:40]: Here it says String? while further up it says String. I assume you meant String here as well?

**Review by provokateurin — APPROVED** [review]

File: packages/neon/neon/lib/src/settings/models/select_option.dart (hunk 4 above)
Comment (Leptopoda) [reply packages/neon/neon/lib/src/settings/models/select_option.dart:40]: `String?` is right although it's debatable wether a type definition for a generic does always implicitly include the null value as well. 

Where did I say plain `String` ?

Comment (provokateurin) [reply packages/neon/neon/lib/src/settings/models/select_option.dart:40]: The plain String is in the comment in the other constructor. I'm fine with both ways, but they should say the same thing

**Review by provokateurin — APPROVED** [review]

**Comment by provokateurin** [comment]
The news app "How to open article" option is still broken :/

**Comment by Leptopoda** [comment]
I'll take a look :sweat_smile:

**Comment by provokateurin** [comment]
But other options in the news settings seem fine
